package dejanuz;
import java.awt.Desktop;
import javax.swing.*;
import java.net.URI;
import java.util.*;



public class DejaGUI extends javax.swing.JFrame {
    
 
    //ListModel for the URL inputs -dc
    DefaultListModel urlNames = new DefaultListModel();

    //ListModel for the results -dc
    DefaultListModel resultsList = new DefaultListModel();

    //ListModel for the test times -dc
    DefaultListModel testTimes = new DefaultListModel();

    //ListModel for the links -dc
    DefaultListModel dejaLinks = new DefaultListModel();
 
    /**
     * Creates new form DejaGUI
     */
    public DejaGUI() { 
                 
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dejaFamPanel = new javax.swing.JPanel();
        dejaInputPanel = new javax.swing.JPanel();
        dejaNuzIt = new javax.swing.JButton();
        dejaTermIn = new javax.swing.JTextField();
        dejaInputLabel = new javax.swing.JLabel();
        dejaOutputPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dejaResultsList = new javax.swing.JList<>();
        resultsLabel = new javax.swing.JLabel();
        dejaJump = new javax.swing.JButton();
        dejaResultsClear = new javax.swing.JButton();
        dejaURLPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urlList = new javax.swing.JList<>();
        dejaURLAdd = new javax.swing.JButton();
        dejaURLRemove = new javax.swing.JButton();
        dejaURLInput = new javax.swing.JTextField();
        dejaClearURL = new javax.swing.JButton();
        dejaNuzLabel = new javax.swing.JLabel();
        dejaCredits = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DejaNuz");
        setBackground(new java.awt.Color(0, 0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        dejaFamPanel.setBackground(new java.awt.Color(0, 0, 0));

        dejaInputPanel.setBackground(new java.awt.Color(100, 100, 100));
        dejaInputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        dejaInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        dejaNuzIt.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        dejaNuzIt.setText("DejaNuz It!");
        dejaNuzIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaNuzItActionPerformed(evt);
            }
        });

        dejaTermIn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dejaTermIn.setText("Trump");
        dejaTermIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaTermInActionPerformed(evt);
            }
        });

        dejaInputLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        dejaInputLabel.setForeground(new java.awt.Color(200, 200, 200));
        dejaInputLabel.setText("Enter a word...");

        javax.swing.GroupLayout dejaInputPanelLayout = new javax.swing.GroupLayout(dejaInputPanel);
        dejaInputPanel.setLayout(dejaInputPanelLayout);
        dejaInputPanelLayout.setHorizontalGroup(
            dejaInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dejaInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dejaTermIn)
                    .addComponent(dejaNuzIt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(dejaInputPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dejaInputLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        dejaInputPanelLayout.setVerticalGroup(
            dejaInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dejaInputPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(dejaInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dejaTermIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dejaNuzIt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dejaOutputPanel.setBackground(new java.awt.Color(100, 100, 100));
        dejaOutputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jScrollPane2.setViewportView(dejaResultsList);

        resultsLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        resultsLabel.setForeground(new java.awt.Color(200, 200, 200));
        resultsLabel.setText("DejaResults");

        dejaJump.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dejaJump.setText("DejaJump Selected!");
        dejaJump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaJumpActionPerformed(evt);
            }
        });

        dejaResultsClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dejaResultsClear.setText("Clear All Results");
        dejaResultsClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaResultsClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dejaOutputPanelLayout = new javax.swing.GroupLayout(dejaOutputPanel);
        dejaOutputPanel.setLayout(dejaOutputPanelLayout);
        dejaOutputPanelLayout.setHorizontalGroup(
            dejaOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaOutputPanelLayout.createSequentialGroup()
                .addGroup(dejaOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dejaOutputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dejaOutputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dejaJump, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dejaResultsClear)))
                .addContainerGap())
            .addGroup(dejaOutputPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(resultsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dejaOutputPanelLayout.setVerticalGroup(
            dejaOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaOutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dejaOutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dejaJump)
                    .addComponent(dejaResultsClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dejaURLPanel.setBackground(new java.awt.Color(100, 100, 100));
        dejaURLPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));

        jScrollPane1.setViewportView(urlList);

        dejaURLAdd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dejaURLAdd.setText("ADD");
        dejaURLAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaURLAddActionPerformed(evt);
            }
        });

        dejaURLRemove.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dejaURLRemove.setText("REMOVE");
        dejaURLRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaURLRemoveActionPerformed(evt);
            }
        });

        dejaClearURL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dejaClearURL.setText("Clear All URLs");
        dejaClearURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejaClearURLActionPerformed(evt);
            }
        });

        dejaNuzLabel.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        dejaNuzLabel.setForeground(new java.awt.Color(200, 200, 200));
        dejaNuzLabel.setLabelFor(dejaResultsList);
        dejaNuzLabel.setText("DejaNuz");

        dejaCredits.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dejaCredits.setText("By: Jabari, Jacob, Dan and Donovan");

        javax.swing.GroupLayout dejaURLPanelLayout = new javax.swing.GroupLayout(dejaURLPanel);
        dejaURLPanel.setLayout(dejaURLPanelLayout);
        dejaURLPanelLayout.setHorizontalGroup(
            dejaURLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaURLPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dejaURLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dejaURLPanelLayout.createSequentialGroup()
                        .addComponent(dejaURLInput, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dejaURLAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dejaURLRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dejaClearURL))
                    .addGroup(dejaURLPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dejaURLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dejaURLPanelLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(dejaCredits))
                            .addGroup(dejaURLPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(dejaNuzLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dejaURLPanelLayout.setVerticalGroup(
            dejaURLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaURLPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dejaURLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(dejaURLPanelLayout.createSequentialGroup()
                        .addComponent(dejaNuzLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dejaCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dejaURLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dejaURLInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dejaURLAdd)
                    .addComponent(dejaURLRemove)
                    .addComponent(dejaClearURL))
                .addContainerGap())
        );

        javax.swing.GroupLayout dejaFamPanelLayout = new javax.swing.GroupLayout(dejaFamPanel);
        dejaFamPanel.setLayout(dejaFamPanelLayout);
        dejaFamPanelLayout.setHorizontalGroup(
            dejaFamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaFamPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(dejaFamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dejaURLPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dejaFamPanelLayout.createSequentialGroup()
                        .addComponent(dejaInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dejaOutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dejaFamPanelLayout.setVerticalGroup(
            dejaFamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dejaFamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dejaFamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dejaOutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dejaInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dejaURLPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(dejaFamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dejaFamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //When they click the DejaNuz Button -dc
    private void dejaNuzItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaNuzItActionPerformed

        //stackoverflow reference but the math is basic number line operation -dc
        long testTimeStart = System.currentTimeMillis();

        long timeUrlStart = System.currentTimeMillis();

        //string to catch the input -dc
        String input = new String(dejaTermIn.getText());

        //passing input into the grooming class -dc
        input = Groom.barber(input);

        //object for display -dc
        Display e = new Display();

        //Clearing the list for the new results -dc
        resultsList.clear();
        
        //array used for Collections methods -dc
        TreeSet rankMe = new TreeSet();

        //feeding the chain into the results box -dc
        for (int i = 0; i <= urlNames.getSize() - 1; i++) {

            rankMe.add(e.results(Search.match(input, Parse.getDat(urlList.getModel().getElementAt(i))), urlList.getModel().getElementAt(i)));

            //Logs time in a list for each query from the start of the first event -dc
            long testTimeEnd = System.currentTimeMillis();
            testTimes.addElement((testTimeEnd - timeUrlStart) + "ms @ " + urlList.getModel().getElementAt(i));
            timeUrlStart = System.currentTimeMillis();
        }

        //total time counting results -dc
        long finalEnd = System.currentTimeMillis();
        testTimes.addElement((finalEnd - testTimeStart) + "ms Total Query Time.");

        //for each element k, add to rankMe:TreeSet -dc
        for (int k = 0; k <= resultsList.getSize() - 1; k++) {
            rankMe.add(resultsList.elementAt(k));

        }
        
        //for each object i in rankMe, add element I to resultsList -dc
        for (Object i : rankMe.descendingSet()) {
            resultsList.addElement(i);
        }

    }//GEN-LAST:event_dejaNuzItActionPerformed


    private void dejaURLAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaURLAddActionPerformed

        //Adding the url from the text box -dc
        if (Groom.urlCheck(dejaURLInput.getText())) {
            urlNames.addElement(dejaURLInput.getText());
            dejaURLInput.setText("");
        }


    }//GEN-LAST:event_dejaURLAddActionPerformed

    private void dejaURLRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaURLRemoveActionPerformed

        //Removes the selected url -dc
        try {
            urlNames.remove(urlList.getSelectedIndex());
        } //Catching that annoying outofbounds exception -dc
        catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Nothing to remove.");
        }

    }//GEN-LAST:event_dejaURLRemoveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        //setting jlist elements to the resultsList model -dc
        dejaResultsList.setModel(resultsList);
    
        //sets up the url jlist -dc
        urlList.setModel(urlNames);
        urlNames.addElement("www.cnbc.com");        
        urlNames.addElement("www.cnn.com");
        urlNames.addElement("www.foxnews.com");
        
    }//GEN-LAST:event_formComponentShown

    private void dejaTermInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaTermInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dejaTermInActionPerformed

    private void dejaJumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaJumpActionPerformed

        //Try and Catch for jumping to a selected results URL -dc
        try {
            String url = (String) LinkExtractor.dejaURLExtractResults((String)resultsList.getElementAt(dejaResultsList.getSelectedIndex()));
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Are you sure you have something selected?", "Just checking.", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_dejaJumpActionPerformed

    private void dejaClearURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaClearURLActionPerformed

        //clearing url list -dc
        urlNames.removeAllElements();
    }//GEN-LAST:event_dejaClearURLActionPerformed

    private void dejaResultsClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejaResultsClearActionPerformed
        resultsList.removeAllElements();
    }//GEN-LAST:event_dejaResultsClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DejaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DejaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DejaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DejaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DejaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dejaClearURL;
    private javax.swing.JLabel dejaCredits;
    private javax.swing.JPanel dejaFamPanel;
    private javax.swing.JLabel dejaInputLabel;
    private javax.swing.JPanel dejaInputPanel;
    private javax.swing.JButton dejaJump;
    private javax.swing.JButton dejaNuzIt;
    private javax.swing.JLabel dejaNuzLabel;
    private javax.swing.JPanel dejaOutputPanel;
    private javax.swing.JButton dejaResultsClear;
    private javax.swing.JList<String> dejaResultsList;
    private javax.swing.JTextField dejaTermIn;
    private javax.swing.JButton dejaURLAdd;
    private javax.swing.JTextField dejaURLInput;
    private javax.swing.JPanel dejaURLPanel;
    private javax.swing.JButton dejaURLRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel resultsLabel;
    public javax.swing.JList<String> urlList;
    // End of variables declaration//GEN-END:variables
}
